site_name: Portfolio
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans 
    code: Red Hat Mono
  logo: assets/favicon.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    # - header.autohide
  # Indigo is #4051B5FF
  palette:
    # Dark mode settings
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Dark Mode 
      primary: indigo
      accent: blue
    # Light mode settings
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode 
      primary: indigo
      accent: blue

plugins:
  - mkdocs-jupyter:
      allow_errors: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true 
    - admonition
    - pymdownx.details
    #- mdx_math

nav:
  - Home: index.md
  - About: about.md
  - Data Engineering:
    - AutoCorp Cloud Data Lake Pipeline: autocorp-database.md
    - AWS Data Lake Pipeline: basic-pipeline.md
  - Data Science:
    - Statistical Distributions:
      - Overview: distributions.md
      - Fundamentals:
        - Distribution Fundamentals: notebooks/dist-01-distribution-fundamentals.ipynb
        - Basic Probability and Expected Value: notebooks/dist-02-basic-prob-and-exp-val.ipynb
        - Standard Deviation and Variance: notebooks/dist-03-std-dev-and-var.ipynb
        - Data Point to Standard Deviation: notebooks/dist-04-data-point-to-std-dev.ipynb
      - Discrete Distributions:
        - Binomial Distributions: notebooks/dist-05-binomial-distributions.ipynb
        - Geometric Distributions: notebooks/dist-06-geometric-distributions.ipynb
        - Poisson Distribution: notebooks/dist-07-poisson.ipynb
      - Sampling and Transformations:
        - Sample Distribution of Sample Mean: notebooks/dist-08-sample-distro-of-sample-mean.ipynb
        - Combinations of Random Variables: notebooks/dist-09-combinations-of-random-vars.ipynb
        - Transforming Random Variables: notebooks/dist-10-transforming-random-variables.ipynb
      - T-Distribution:
        - T-Distribution: notebooks/dist-11-t-distribution.ipynb
        - Student T-Distribution: notebooks/dist-12-student-t-distribution.ipynb
    - Hypothesis Testing:
      - Overview: hypothesis-testing.md
      - Introduction to P-Value: notebooks/ht-01-intro-to-pvalue.ipynb
      - One-Tail and Two-Tail Tests (Means): notebooks/ht-02-one-two-tail-test-diff-mean.ipynb
      - One-Tail and Two-Tail Tests (Proportions): notebooks/ht-03-one-two-tail-test-diff-props.ipynb
      - Chi-Squared Test: notebooks/ht-04-chi-squared.ipynb
      - Regression Hypothesis Testing: notebooks/ht-05-regression-hypothesis.ipynb
  - Machine Learning:
    - Heart Disease Prediction: heart-disease.ipynb
  - Cloud Computing:
    - AWS Management: aws-management.md
    - AWS File Validator: aws-file-validator.md
    - Scotton AWS Utils: scotton-aws-utils.md
    - Terraform AWS Product App: terraform-aws-product-app.md
    - DynamoDB Inventory System: dynamodb-inventory-system.md

extra:
  social:
    - icon: fontawesome/solid/globe-americas
      link: /about/
      name: About
    - icon: fontawesome/solid/shield-halved
      link: https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement
      name: Privacy Policy
    - icon: fontawesome/solid/envelope
      link: mailto:stevenwcotton@gmail.com
      name: Email
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/steven-cotton-7948157
      name: LinkedIn
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/stevenwcotton.bsky.social
      name: Bluesky

copyright: Copyright &copy; 2018 - 2025 Steven Cotton